export const ProjectStateErrorCode = {
  TRACK_NOT_FOUND: 'TRACK_NOT_FOUND',
  TRACK_ID_CONFLICT: 'TRACK_ID_CONFLICT',
  REGION_NOT_FOUND: 'REGION_NOT_FOUND',
  REGION_ID_CONFLICT: 'REGION_ID_CONFLICT',
  AMBIGUOUS_REGION_TARGET: 'AMBIGUOUS_REGION_TARGET',
  INVALID_SPLIT_POSITION: 'INVALID_SPLIT_POSITION',
  INVALID_REGION_POSITION: 'INVALID_REGION_POSITION',
  INVALID_REGION_TIMELINE_RANGE: 'INVALID_REGION_TIMELINE_RANGE',
  INVALID_REGION_SOURCE_RANGE: 'INVALID_REGION_SOURCE_RANGE',
  REGION_SOURCE_MISSING: 'REGION_SOURCE_MISSING',
  REGION_SOURCE_RANGE_EXCEEDED: 'REGION_SOURCE_RANGE_EXCEEDED',
  REGION_DURATION_REQUIRED: 'REGION_DURATION_REQUIRED',
  INVALID_EXPORT_RANGE: 'INVALID_EXPORT_RANGE',
  PLUGIN_MANIFEST_NOT_FOUND: 'PLUGIN_MANIFEST_NOT_FOUND',
  PLUGIN_INSTANCE_ID_CONFLICT: 'PLUGIN_INSTANCE_ID_CONFLICT',
  PLUGIN_INSTANCE_NOT_FOUND: 'PLUGIN_INSTANCE_NOT_FOUND',
  PLUGIN_TARGET_INDEX_OUT_OF_RANGE: 'PLUGIN_TARGET_INDEX_OUT_OF_RANGE',
  PLUGIN_PARAMETER_NOT_FOUND: 'PLUGIN_PARAMETER_NOT_FOUND',
  INVALID_PLUGIN_PARAMETER_VALUE: 'INVALID_PLUGIN_PARAMETER_VALUE',
} as const;

export type ProjectStateErrorCode = (typeof ProjectStateErrorCode)[keyof typeof ProjectStateErrorCode];

export class ProjectStateError extends Error {
  constructor(
    public readonly code: ProjectStateErrorCode,
    message: string,
    public readonly details?: Readonly<Record<string, unknown>>
  ) {
    super(message);
    this.name = 'ProjectStateError';
  }
}
